//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pocACIAF.SubtractionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Subtraction")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MathData", Namespace="http://schemas.datacontract.org/2004/07/Subtraction")]
    [System.SerializableAttribute()]
    public partial class MathData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FArg1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FArg2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FRsltArgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrArg1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrArg2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrConcatRsltField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FArg1 {
            get {
                return this.FArg1Field;
            }
            set {
                if ((this.FArg1Field.Equals(value) != true)) {
                    this.FArg1Field = value;
                    this.RaisePropertyChanged("FArg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FArg2 {
            get {
                return this.FArg2Field;
            }
            set {
                if ((this.FArg2Field.Equals(value) != true)) {
                    this.FArg2Field = value;
                    this.RaisePropertyChanged("FArg2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FRsltArg {
            get {
                return this.FRsltArgField;
            }
            set {
                if ((this.FRsltArgField.Equals(value) != true)) {
                    this.FRsltArgField = value;
                    this.RaisePropertyChanged("FRsltArg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrArg1 {
            get {
                return this.StrArg1Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrArg1Field, value) != true)) {
                    this.StrArg1Field = value;
                    this.RaisePropertyChanged("StrArg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrArg2 {
            get {
                return this.StrArg2Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrArg2Field, value) != true)) {
                    this.StrArg2Field = value;
                    this.RaisePropertyChanged("StrArg2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrConcatRslt {
            get {
                return this.StrConcatRsltField;
            }
            set {
                if ((object.ReferenceEquals(this.StrConcatRsltField, value) != true)) {
                    this.StrConcatRsltField = value;
                    this.RaisePropertyChanged("StrConcatRslt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubtractionService.ISubtraction")]
    public interface ISubtraction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubtraction/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISubtraction/GetDataUsingDataContractResponse")]
        pocACIAF.SubtractionService.CompositeType GetDataUsingDataContract(pocACIAF.SubtractionService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubtraction/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISubtraction/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<pocACIAF.SubtractionService.CompositeType> GetDataUsingDataContractAsync(pocACIAF.SubtractionService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubtraction/SubtractArray", ReplyAction="http://tempuri.org/ISubtraction/SubtractArrayResponse")]
        pocACIAF.SubtractionService.MathData[] SubtractArray(pocACIAF.SubtractionService.MathData[] md);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubtraction/SubtractArray", ReplyAction="http://tempuri.org/ISubtraction/SubtractArrayResponse")]
        System.Threading.Tasks.Task<pocACIAF.SubtractionService.MathData[]> SubtractArrayAsync(pocACIAF.SubtractionService.MathData[] md);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubtractionChannel : pocACIAF.SubtractionService.ISubtraction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubtractionClient : System.ServiceModel.ClientBase<pocACIAF.SubtractionService.ISubtraction>, pocACIAF.SubtractionService.ISubtraction {
        
        public SubtractionClient() {
        }
        
        public SubtractionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubtractionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubtractionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubtractionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public pocACIAF.SubtractionService.CompositeType GetDataUsingDataContract(pocACIAF.SubtractionService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<pocACIAF.SubtractionService.CompositeType> GetDataUsingDataContractAsync(pocACIAF.SubtractionService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public pocACIAF.SubtractionService.MathData[] SubtractArray(pocACIAF.SubtractionService.MathData[] md) {
            return base.Channel.SubtractArray(md);
        }
        
        public System.Threading.Tasks.Task<pocACIAF.SubtractionService.MathData[]> SubtractArrayAsync(pocACIAF.SubtractionService.MathData[] md) {
            return base.Channel.SubtractArrayAsync(md);
        }
    }
}
