//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pocACIAF.AdditionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Addition")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MathData", Namespace="http://schemas.datacontract.org/2004/07/Addition")]
    [System.SerializableAttribute()]
    public partial class MathData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FArg1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FArg2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FRsltArgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrArg1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrArg2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrConcatRsltField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FArg1 {
            get {
                return this.FArg1Field;
            }
            set {
                if ((this.FArg1Field.Equals(value) != true)) {
                    this.FArg1Field = value;
                    this.RaisePropertyChanged("FArg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FArg2 {
            get {
                return this.FArg2Field;
            }
            set {
                if ((this.FArg2Field.Equals(value) != true)) {
                    this.FArg2Field = value;
                    this.RaisePropertyChanged("FArg2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FRsltArg {
            get {
                return this.FRsltArgField;
            }
            set {
                if ((this.FRsltArgField.Equals(value) != true)) {
                    this.FRsltArgField = value;
                    this.RaisePropertyChanged("FRsltArg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrArg1 {
            get {
                return this.StrArg1Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrArg1Field, value) != true)) {
                    this.StrArg1Field = value;
                    this.RaisePropertyChanged("StrArg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrArg2 {
            get {
                return this.StrArg2Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrArg2Field, value) != true)) {
                    this.StrArg2Field = value;
                    this.RaisePropertyChanged("StrArg2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrConcatRslt {
            get {
                return this.StrConcatRsltField;
            }
            set {
                if ((object.ReferenceEquals(this.StrConcatRsltField, value) != true)) {
                    this.StrConcatRsltField = value;
                    this.RaisePropertyChanged("StrConcatRslt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdditionService.IAddition")]
    public interface IAddition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddition/GetData", ReplyAction="http://tempuri.org/IAddition/GetDataResponse")]
        pocACIAF.AdditionService.GetDataResponse GetData(pocACIAF.AdditionService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddition/GetData", ReplyAction="http://tempuri.org/IAddition/GetDataResponse")]
        System.Threading.Tasks.Task<pocACIAF.AdditionService.GetDataResponse> GetDataAsync(pocACIAF.AdditionService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddition/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAddition/GetDataUsingDataContractResponse")]
        pocACIAF.AdditionService.GetDataUsingDataContractResponse GetDataUsingDataContract(pocACIAF.AdditionService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddition/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAddition/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<pocACIAF.AdditionService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(pocACIAF.AdditionService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddition/AddUD", ReplyAction="http://tempuri.org/IAddition/AddUDResponse")]
        pocACIAF.AdditionService.AddUDResponse AddUD(pocACIAF.AdditionService.AddUDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddition/AddUD", ReplyAction="http://tempuri.org/IAddition/AddUDResponse")]
        System.Threading.Tasks.Task<pocACIAF.AdditionService.AddUDResponse> AddUDAsync(pocACIAF.AdditionService.AddUDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public pocACIAF.AdditionService.CompositeType composite;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(pocACIAF.AdditionService.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public pocACIAF.AdditionService.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(pocACIAF.AdditionService.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public pocACIAF.AdditionService.MathData[] md;
        
        public AddUDRequest() {
        }
        
        public AddUDRequest(pocACIAF.AdditionService.MathData[] md) {
            this.md = md;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public pocACIAF.AdditionService.MathData[] AddUDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public pocACIAF.AdditionService.MathData[] md;
        
        public AddUDResponse() {
        }
        
        public AddUDResponse(pocACIAF.AdditionService.MathData[] AddUDResult, pocACIAF.AdditionService.MathData[] md) {
            this.AddUDResult = AddUDResult;
            this.md = md;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdditionChannel : pocACIAF.AdditionService.IAddition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditionClient : System.ServiceModel.ClientBase<pocACIAF.AdditionService.IAddition>, pocACIAF.AdditionService.IAddition {
        
        public AdditionClient() {
        }
        
        public AdditionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public pocACIAF.AdditionService.GetDataResponse GetData(pocACIAF.AdditionService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<pocACIAF.AdditionService.GetDataResponse> GetDataAsync(pocACIAF.AdditionService.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public pocACIAF.AdditionService.GetDataUsingDataContractResponse GetDataUsingDataContract(pocACIAF.AdditionService.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<pocACIAF.AdditionService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(pocACIAF.AdditionService.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public pocACIAF.AdditionService.AddUDResponse AddUD(pocACIAF.AdditionService.AddUDRequest request) {
            return base.Channel.AddUD(request);
        }
        
        public System.Threading.Tasks.Task<pocACIAF.AdditionService.AddUDResponse> AddUDAsync(pocACIAF.AdditionService.AddUDRequest request) {
            return base.Channel.AddUDAsync(request);
        }
    }
}
